### PR TITLE
Org name change

### LINKED ISSUE #33: [ORG NAME CHANGE]: Update repo to hubverse-org organisation name
## :exclamation: Please do not merge anything into main until the 19th June

- [x] Create new branch called `to-hubverse` from latest dev branch (most likely related to the v3 schema PRs). (Make sure to pull first). If none exist, branch off from `main`.
- [x] Find and replace `Infectious-Disease-Modeling-Hubs` with `hubverse-org` throughout repo.
- [x] Replace origin remote to point to the new organisation
    ```bash
    git remote set-url origin https://github.com/hubverse-org/<REPO_NAME>.git
    # Check remotes
    git remote -v
    ```
    ```r
    url <- paste0('https://github.com/hubverse-org/', basename(getwd()), '.git')
    usethis::use_git_remote(name = "origin", url, overwrite = TRUE)
    # Check remotes
    usethis::git_remotes()
    ```
- [x] Push and open PR to original branch.

### PR DESCRIPTION
**Pull request by LucieContamin**
Update repository to hubverse-org organisation name

closes #33

### CODE REVIEW

**Review by annakrystalli — APPROVED** [review]
All good! Thanks @LucieContamin

**Comment by annakrystalli** [comment]
Actually, my bad, I forgot to add to the issue. Could you bump the package version number also?

**Comment by LucieContamin** [comment]
> Actually, my bad, I forgot to add to the issue. Could you bump the package version number also?

Done! Sorry I forgot that one too!

**Review by annakrystalli — APPROVED** [review]
Thank you @LucieContamin !

**Pull request merged**
